name: Build Maven App
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: client-manager-artifact
        path: target/Trui-0.0.1-SNAPSHOT.war

    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
