name: Run Maven
on: [push, pull_request]
jobs:
  maven:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: |
          17
          11
          8
        distribution: temurin
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
